These scripts use the https://wiki.duraspace.org/display/FEDORA38/REST+API#RESTAPI-API-AMethods[Fedora REST APIs].

== Required permissions

To run these scripts, you will need to be able to access your Islandora instance's Fedora server from the machine on which you are using the scripts. *Talk to whoever administers your Islandora instance if you run into problems with the steps below.*

Before running any of these scripts, set up local port forwarding:

`ssh -L {local_port}:localhost:8080 {username}@{my-fedora-server.org} -p {fedoraserverport}`

- `local_port` = port on your local machine you'll use for this connection. Any random port number that is not in use should work.
- `username` = the user name you use to connect to the Fedora server
- `my-fedora-server.org` = host name of your Fedora server
- `fedoraserverport` = port to connect to on the Fedora server -- Whether this is needed depends on how your Fedora server is set up. If you don't need this, remove `-p` and everything after.

If you were able to log in with that command, great! Now paste this into your browser, replacing `local_port` with the number you chose:

`http://localhost:{local_port}/fedora`

See Fedora's repository information view? If so, you should be able to proceed.

Remember the scripts will only work if you can also see that page in your browser! 

== General usage

You'll run these scripts via a command with the following general pattern:

`ruby scriptname.rb -p {local_port} -i {input_file} -o {output_file_or_directory}`

- `local_port` = same as you set up above
- `input_file` = usually a list of Fedora persistent identifiers (PIDs) in the format: `namespace:id`. Variations on this detailed per script, in its README.
- `output_file_or_directory` = where you want the results to be put. Variations detailed per script, in its README.

